---
- include_tasks:        'tasks/common/create_files.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/enable_services.yml'
- include_tasks:        'tasks/common/start_services.yml'
- include_tasks:        'tasks/common/restart_services.yml'
  when:                 create_files_result.changed
                        or install_files_result.changed
                        or symlinks_result.changed
