---
- include_tasks:        '../tasks/create_files.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/start_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 create_files_result.changed
                        or install_files_result.changed
                        or symlinks_result.changed
